### ISSUE TITLE
Bumper master checklist

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/bumper#1]
## Implementation
- [x] **Repository created** (Date: 01/10/2018)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos (then `grunt generate-data` in perennial and check in)

**Comment by phet-steele** [comment]
@ariel-phet do we need this issue for this repo?

**Comment by ariel-phet** [comment]
Checklist trimmed significantly. Closing
